### ISSUE TITLE
Roving hackers are e-mailing me about API keys in this repository

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/duos-ui#884]
I got an e-mail from one Beny Coninteil complaining that there are what look like API keys publicly available in this repository.

https://github.com/DataBiosphere/duos-ui/blob/b517cc9fca250c54bfdfffc1975016d487c20e51/config/prod.json#L7-L8

Are these keys meant to be kept secret? If not, can they be stored in a format that supports a comment explaining why they do not have to be kept secret?

**Comment by rushtong** [comment]
@adamnovak 
These are not secrets, they are publicly accessible values through the application. We can remove them from the repo. We've been notified from internal sources as well and will address this in an upcoming PR. Thank you.

**Comment by rushtong** [comment]
Resolved with https://github.com/DataBiosphere/duos-ui/pull/879
